name: Ruff (Linter and Formatter)

on:
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'ruff.toml'

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."

      - name: Run Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."